parameters:
#    eldar_blog.example.class: Eldar\BlogBundle\Example

services:
#    eldar_blog.example:
#        class: %eldar_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
